baseURL = "http://example.org/"
languageCode = "en-us"
summaryLength = 15
title = "Psicólogo Paulo Alves"

theme = "lugo"

[params]
	main_page = "Paulo Alves"
	main_page_under = "Psicólogo Clínico"

[menu]
	[[menu.main]]
		name = "Procrastinação e Gestão do Tempo" 
		url= "/gt/" 
		weight = 1
	[[menu.main]]
		name = "Terapia" 
		url= "/psicoterapia/" 
		weight = 2
	[[menu.main]]
		name = "Postagens"
		url="/blog/"
		weight = 3
	[[menu.main]]
		name = "Contato" 
		url= "/contato/" 
		weight = 4
	[[menu.main]]
		name = "Sobre" 
		url= "/sobre/" 
		weight = 5

