baseURL = "http://paulorssalves.com.br/"
languageCode = "pt-br"
summaryLength = 15
title = "Paulo Alves | Psicólogo | Procrastinação e Gestão do Tempo"

theme = "lugo"

[params]
	main_page = "Paulo Alves"
	main_page_under = "Psicólogo Clínico"

[menu]
	[[menu.main]]
		name = "Gestão do tempo" 
		url= "/blog/gt/" 
		weight = 1
	[[menu.main]]
		name = "Terapia" 
		url= "/blog/terapia/" 
		weight = 2
	[[menu.main]]
		name = "Postagens"
		url="/blog/"
		weight = 3
	[[menu.main]]
		name = "Contato" 
		url= "/contato/" 
		weight = 4
	[[menu.main]]
		name = "Sobre" 
		url= "/sobre/" 
		weight = 5

